"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yky45*rz(_#(lrg&ul5askffrikqb5z#n-n-$5sxyci)!n*c1%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    # '192.168.1.10:8000', 
    # 'http://localhost:3000',
    # 'http://127.0.0.1:3000',
    # 'your-domain.com',
    # 'api.your-domain.com',
    # '192.168.1.10',
    'localhost',
    '127.0.0.1',
    '192.168.1.254'
    # '*',
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    # "x_auth",  # Add your custom header here
    "auth",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # myInput
    'items.apps.ItemsConfig',
    'repositories.apps.RepositoriesConfig',
    'users.apps.UsersConfig',
    'permissions.apps.PermissionsConfig',
    'user_management.apps.UserManagementConfig',
    'invoices.buyer_supplier_party.apps.BuyerSupplierPartyConfig',
    'transfer_items',
    'invoices.purchase.apps.PurchaseConfig',
    'invoices.sales.apps.SalesConfig',
    'rest_framework',
    'django_filters',
    "corsheaders",
    'django_cleanup.apps.CleanupConfig',
    
    'finance.debt_settlement.apps.DebtSettlementConfig',
    'finance.expenses.apps.ExpensesConfig',
    'finance.vault_and_methods.apps.VaultAndMethodsConfig',
    'finance.payment.apps.PaymentConfig',
    'finance.reverse_payment.apps.ReversePaymentConfig',
    'finance.transfer.apps.TransferConfig',
    "common",
    "employees.apps.EmployeesConfig",
    "refillable_items_system",

    "requests_logs",
    "django_extensions",

    'debug_toolbar',
    'services',
]

#################################
# regarding to run server as https
#################################
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

MIDDLEWARE = [
    # my input
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    # "debug_toolbar.middleware.DebugToolbarMiddleware",

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # my input
    # 'backend.middleware.JSONOnlyMiddleware',
    'backend.middleware.RequestLogMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
          os.path.join(BASE_DIR, 'dist'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'e-commerce',
        'USER': 'postgres',
        'PASSWORD': 'BeWithAllah',
        'HOST': 'db',
        # 'HOST': 'localhost',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# my input
# 
# 
# 
LANGUAGE_CODE = "ar-eg"
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'apps.core.pagination.StandardResultsSetPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'auth.authentication.CustomAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # 'auth.permissions.IsLoggedIn',
        'auth.permissions.DynamicPermission',
        # Note: RequirePasswordChangePermission removed from here
        # It was blocking ALL requests. Better to check in middleware or login.
    ),
}

# STATIC_URL = 'dist/'

STATICFILES_DIRS = [
    BASE_DIR / "dist",
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = [
#     "https://example.com",
#     "https://sub.example.com",
#     "http://localhost:5173",
#     "http://localhost:3000",
#     "http://127.0.0.1:5173",
#     "http://127.0.0.1:3000",
# ]
# if we dont set this the client side won't be able to get cookies that we set in server side
CORS_ALLOW_CREDENTIALS = True

# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:3000',
#     'http://127.0.0.1:3000',
# ]

# CSRF_COOKIE_SECURE = False
# CSRF_COOKIE_HTTPONLY = False
# CSRF_COOKIE_SAMESITE = 'Lax'

# Add this line to your existing CSRF settings
# CSRF_COOKIE_NAME = 'csrftoken'  # Make sure this matches what you're looking for
# CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
# CSRF_USE_SESSIONS = False  # Use cookies, not sessions
# CSRF_COOKIE_AGE = 31449600  # One year


AUTH_USER_MODEL = 'users.User'

# 
# jwt secret key
JWT_SECRET_KEY = 'o2)fe2j^FF(823h9f0F(#hsh8H*&#^ois&(&f*Fd9f977d&F65d)ij)'

APPEND_SLASH = False

# ALLOWED_CONTENT_TYPES = [
#     'application/json',
#     'application/xml',
#     'multipart/form-data',
#     # Add any other content types you want to allow
# ]


# my input
# LOGGING = {
#     'version': 1,
#     'filters': {
#         'require_debug_true': {
#             '()': 'django.utils.log.RequireDebugTrue',
#         }
#     },
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'filters': ['require_debug_true'],
#             'class': 'logging.StreamHandler',
#         }
#     },
#     'loggers': {
#         'django.db.backends': {
#             'level': 'DEBUG',
#             'handlers': ['console'],
#         }
#     }
# }

# debug_toolbar app config

# The Debug Toolbar is shown only if your IP address is listed in Django’s INTERNAL_IPS setting.
INTERNAL_IPS = [
    "127.0.0.1",
]
